### PR TITLE
feat: added function to read the contents from yml

### PR DESCRIPTION
**Pull request by KushalJetty**
```
2024/12/28 20:50:28 fetching content from yaml file of repository
[GIN] 2024/12/28 - 20:50:28 | 204 |            0s |   140.82.115.77 | POST     "/webhook"
2024/12/28 20:50:28 Successfully fetched content for file: codesourcerer-config.yml
2024/12/28 20:50:28 YAML Contents:
2024/12/28 20:50:28 Test Directory: tests
2024/12/28 20:50:28 Comments: on
2024/12/28 20:50:28 Testing Branch: main
2024/12/28 20:50:28 Testing Framework: pytest
2024/12/28 20:50:28 Water Mark: on
2024/12/28 20:50:28 Redis Caching: off
2024/12/28 20:50:29 Dependencies from PR Description: map[r2.py:[q1.py] r3.py:[r2.py]]
2024/12/28 20:50:29 Context: This PR is calculating factorial and combination
```

### CODE REVIEW

**Comment by puneeth072003** [comment]
> Test Directory: tests

Insted of this please log the path

> 2024/12/28 20:50:29 Dependencies from PR Description: map[r2.py:[q1.py] r3.py:[r2.py]]
> 2024/12/28 20:50:29 Context: This PR is calculating factorial and combination

If these content are from your function, then please remove these, these are not needed.

while at it, please provide me the `codesourcerer-config.yaml` contents so that i can approve it.

**Comment by KushalJetty** [comment]
No these are not from the yaml file it is from your file

**Comment by puneeth072003** [comment]
can you please comment your entire yaml file content here.

**Comment by puneeth072003** [comment]
> No these contents are not from the yaml they are just next lines

all good then

**Comment by KushalJetty** [comment]
Yml file is in testincs repository

**Comment by puneeth072003** [comment]
@KushalJetty Can you complete the changes ASAP

**Comment by puneeth072003** [comment]
# Further updations

modify the below snippet in `initalwebhookhandler.go` to accomadate your data.

please don't change the structure as of now.

```go
responseData := struct {
				MergeID       string `json:"merge_id"`
				Context       string `json:"context"`
				Framework     string `json:"framework"`
				TestDirectory string `json:"test_directory"`
				Comments      string `json:"comments"`
				Files         []struct {
					Path         string `json:"path"`
					Content      string `json:"content"`
					Dependencies []struct {
						Name    string `json:"name"`
						Content string `json:"content"`
					} `json:"dependencies"`
				} `json:"files"`
			}{
				MergeID:       mergeID,
				Context:       context,
				Framework:     "pytest", // Hardcoded framework
				TestDirectory: "tests/", // Hardcoded test directory
				Comments:      "off",    // Hardcoded comments setting
			}
```

**Comment by puneeth072003** [comment]
> Yml file contents is in testincs repository

yeahh i know that, show me the sample

**Comment by KushalJetty** [comment]
test-directory: "tests"
comments: "on"
testing-branch: "main"
testing-framework: "pytest"
water-mark: "on"
redis-caching: "off"

**Comment by puneeth072003** [comment]
> test-directory: "tests"
comments: "on"
testing-branch: "main"
testing-framework: "pytest"
water-mark: "on"
redis-caching: "off"

better modify the above to below format.

```yml
configuration:
  test-directory: "tests"
  comments: "on"
  testing-branch: "main"
  testing-framework: "pytest"
  water-mark: "on"

# logging:
#   level: "info"
#   format: "json"
#   enable-file-logging: true
#   log-file: "app.log"

# notifications:
#   PR-comments: "enabled"

environment:
  python-version: "3.10"

caching:
  enabled: false
  redis-caching: "off"
```

**Comment by KushalJetty** [comment]
hey i have already used the structure to store the contents of yaml in fetchymlcontent.go

```
**

> type Config struct {
> 	TestDirectory    string `yaml:"test-directory"`
> 	Comments         string `yaml:"comments"`
> 	TestingBranch    string `yaml:"testing-branch"`
> 	TestingFramework string `yaml:"testing-framework"`
> 	WaterMark        string `yaml:"water-mark"`
> 	RedisCaching     string `yaml:"redis-caching"`
> }

**

// FetchAndLogYAMLContents fetches and logs specific YAML contents
func FetchAndLogYAMLContents(owner, repo, commitSHA, filePath string) error {
	// Fetch the file content from GitHub
	content, err := FetchFileContentFromGitHub(owner, repo, commitSHA, filePath)
	if err != nil {
		return err
	}

	// Parse YAML content
	var config Config
	err = yaml.Unmarshal([]byte(content), &config)
	if err != nil {
		return err
	}

	// Log the contents
	log.Printf("YAML Contents:\n")
	log.Printf("Test Directory: %s", config.TestDirectory)
	log.Printf("Comments: %s", config.Comments)
	log.Printf("Testing Branch: %s", config.TestingBranch)
	log.Printf("Testing Framework: %s", config.TestingFramework)
	log.Printf("Water Mark: %s", config.WaterMark)
	log.Printf("Redis Caching: %s", config.RedisCaching)

	return nil
}

```

**Comment by KushalJetty** [comment]
> hey i have already used the structure to store the contents of yaml in fetchymlcontent.go
> 
> ```
> 
> ```
> 
> **type Config struct { TestDirectory string `yaml:"test-directory"` Comments string `yaml:"comments"` TestingBranch string `yaml:"testing-branch"` TestingFramework string `yaml:"testing-framework"` WaterMark string `yaml:"water-mark"` RedisCaching string `yaml:"redis-caching"` }**
> 
> ```
> 
> // FetchAndLogYAMLContents fetches and logs specific YAML contents
> func FetchAndLogYAMLContents(owner, repo, commitSHA, filePath string) error {
> 	// Fetch the file content from GitHub
> 	content, err := FetchFileContentFromGitHub(owner, repo, commitSHA, filePath)
> 	if err != nil {
> 		return err
> 	}
> 
> 	// Parse YAML content
> 	var config Config
> 	err = yaml.Unmarshal([]byte(content), &config)
> 	if err != nil {
> 		return err
> 	}
> 
> 	// Log the contents
> 	log.Printf("YAML Contents:\n")
> 	log.Printf("Test Directory: %s", config.TestDirectory)
> 	log.Printf("Comments: %s", config.Comments)
> 	log.Printf("Testing Branch: %s", config.TestingBranch)
> 	log.Printf("Testing Framework: %s", config.TestingFramework)
> 	log.Printf("Water Mark: %s", config.WaterMark)
> 	log.Printf("Redis Caching: %s", config.RedisCaching)
> 
> 	return nil
> }
> ```

is this what u expected or u were referring for other method?

**Pull request closed without merging**
