### PR TITLE
fix: Fix all gosec Security Issues

### PR DESCRIPTION
**Pull request by soorya-u**

### CODE REVIEW

**Comment by puneeth072003** [comment]
@soorya-u i think we should modify the worklow to actually install depenedencies first (in both services ig)

**Comment by puneeth072003** [comment]
> > @soorya-u i think we should modify the worklow to actually install depenedencies first (in both services ig) to get this working
> 
> yea...apart from that...the security issues are fixed

Yes but worklfow is failing we need to fix that for further runs

**Comment by puneeth072003** [comment]
@soorya-u please cache previous depenedincies to that it doesn't take up much CI minutes everytime

**Comment by soorya-u** [comment]
> @soorya-u please cache previous depenedencies to that it doesn't take up much of CI minutes everytime

Done

**Comment by puneeth072003** [comment]
@soorya-u you are good to go, good work!!!

**Comment by puneeth072003** [comment]
once after merging check the workflow is passing or not

**Comment by puneeth072003** [comment]
you might need to make series of changes if not

**Review by puneeth072003 — APPROVED** [review]
good to go

**Pull request merged**
