### PR TITLE
fix: Added URL Param Parsing for better security

### LINKED ISSUE #31: Fix code scanning alert - Uncontrolled data used in network request
Tracking issue for:
- [ ] https://github.com/puneeth072003/CODESOURCERER/security/code-scanning/3
- [ ] https://github.com/puneeth072003/CODESOURCERER/security/code-scanning/4

### PR DESCRIPTION
**Pull request by soorya-u**
closes #31

### CODE REVIEW

**Comment by soorya-u** [comment]
@puneeth072003 Can you modify workflow to make sure it checks for security issues on every PR

**Comment by puneeth072003** [comment]
> @puneeth072003 Can you modify workflow to make sure it checks for security issues on every PR

yep, gimme some time.

**Comment by puneeth072003** [comment]
> @puneeth072003 Can you modify workflow to make sure it checks for security issues on every PR

Actually, i have intentionally disabled the gosec workflow. do you want me to enable it again?
Cuz it mentioned 4-5 issues that needs to be fixed on the workflow run.

as mentioned in this https://github.com/puneeth072003/CODESOURCERER/issues/17

**Comment by soorya-u** [comment]
Just make sure to Add CodeQL checks on every PR. That way we can fix the security issues in the same PR for the future PR. 

As for this PR, I can only know if this fixes the Issue only after merging to main branch which is not ideal. So if the CodeQL checks are passed for this PR, then the issue will be fixed.

**Pull request merged**
